### ISSUE TITLE
Since 1.5.3 redstone comparator does not work

### ISSUE THREAD

**Issue by FightMan01** [TeamAOF/All-of-Fabric-6#202]
Since 1.5.3 redstone comparator does not work until I cause a block update like placing a block next to it. I don't know whether this is a powah! issue, aof issue or just a minecraft bug on our world. Video attached

https://user-images.githubusercontent.com/29693718/233400037-c95a281c-c6de-4900-94d0-b13a76a62a03.mp4

**Comment by James103** [comment]
1. Are you able to reproduce this in a separate (testing) world?
2. Does the comparator work when used to read the contents from a vanilla container (chest, barrel, hopper, dispenser)?

**Comment by jpenilla** [comment]
This also happens with the Fluix Mana Pool. I don't think it's a Powah issue.

**Comment by FightMan01** [comment]
@James103 
I have tested this with a chest, the issue is the same.
However trying in a single player, newly generated world the comparator works as intended. So in general I would say that the issue affects the multiplayer server when it is upgraded from 1.5.2 to 1.5.3.

**Comment by mim1q** [comment]
I've updated Mine Cells with the fix applied. [Modrinth](https://modrinth.com/mod/minecells/version/1.4.3), CurseForge is under review.

**Comment by aruss69xd** [comment]
I thought I`m going crazy with my item frame piston door xD

**Comment by ImAK9** [comment]
fixed in 1.5.4

**Comment by u6bkep** [comment]
This still appears to be broken. We have confirmed it with vanilla hopper clock, and with Create stress meters.
