### ISSUE TITLE
Hex Casting v0.10.2 has a bug preventing advanced spells from working

### ISSUE THREAD

**Issue by mtakemoto** [TeamAOF/All-of-Fabric-6#41]
I was in the Hex Casting discord trying to get a conditional spell to work and ran into this.  Original issue from Hex Casting repo:
https://github.com/gamma-delta/HexMod/issues/339

It's been confirmed to be fixed in v0.10.3.  Can you please update this in the next release?  Thank you!

**Comment by dandin87** [comment]
This is already fixed in the latest AoF6. But you have to run a command to actually fix it since most worlds were created with the bugged version. 
`/hexcasting recalcPatterns`
There is nothing we can do about this. This command must be run to fix it.

**Comment by mtakemoto** [comment]
I'm still seeing the default Hex Casting .jar file come in as 0.10.2 in AoF6 v1.0.2.  I just dropped the new .jar version into my client and server and that fixed the new spell I wrote.  I didn't have any existing patterns that needed to be fixed but thanks for showing me that command.

I also don't see the modlist or patch notes mention the version bump either.

**Comment by dandin87** [comment]
oh? Perhaps this is actually a different bug then what I was talking about. In that case it should be fixed when we next update then.
